### ISSUE TITLE
Remove the update notifier

### ISSUE THREAD

**Issue by duganchen** [qbasicer/qzdl#36]
The Update Notifier isn't exactly a useful feature. It currently checks a dead URL, and we all know it's been years since there have been updates to notify of.

Apart from that, it uses the QHttp class, which is gone in Qt 5. While rewriting it to follow current Qt best practices (QNetworkAccessManager) is an option, I'd recommend just removing it. The Update Notifier is the only part of the codebase that uses QHttp.

So let's just take this part out, and we'll consider that the first step towards the port to Qt 5.

I intend to have a pull request for this up soon.

**Comment by qbasicer** [comment]
I'm ok with this, I had left it around intentionally so that if the project was taken over, I'd trigger an update so that everybody migrates to the new version.  This hasn't happened yet, and anybody building from git won't care about updates anyways.
