### ISSUE TITLE
Cant build, qeglfshooks_p.h doesn't exist.

### ISSUE THREAD

**Issue by failster** [qbasicer/qzdl#40]
When I try to run the configure file it outputs this error:

`mkspecs/devices/linux-arm-amlogic-8726M-g++/qeglfshooks_8726m.cpp:40:10: fatal error: 
      'private/qeglfshooks_p.h' file not found`

In case it's needed:
OS: macOS Sierra
Version: 10.12.4 Beta
Model: MacBook Pro (13-inch, Mid 2012)
Processor: 2.5 GHz Intel Core i5
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 4000 1536 MB

**Comment by tejaskhorana** [comment]
Hi, I'm running into the exact same issue when compiling my C++ project using 'make' on a similar spec'd Mac. Do you mind telling me how you resolved this issue? Thanks!
