### ISSUE TITLE
Uhm, are you dead?

### ISSUE THREAD

**Issue by duganchen** [qbasicer/qzdl#48]
Please reply so that we know that you (qbasicer, the maintainer) is not physically dead.

Thanks.

**Comment by qbasicer** [comment]
Not dead, just haven't had time to check github.

I'm (obviously) not maintaining ZDL, so I can't do much about the current issues.  I certainly do not have the infrastructure to generate binaries for Windows.  I did not see the pull request you raised, and if you'd like to take the project over, I'd certainly be open to it.

Please contact me personally on gmail.  Address should be obvious :)
