### ISSUE TITLE
No Options Listed for "Source Port"

### ISSUE THREAD

**Issue by delp** [qbasicer/qzdl#58]
I'm on debian and I have GZDOOM installed.

qzdl built fine and is running, but theres nothing in the source port drop down. How do I help it find my engines?

**Comment by duganchen** [comment]
![add_source_port](https://user-images.githubusercontent.com/447610/70855879-f8645f80-1e86-11ea-9efc-8aa8629a6dac.png)

**Comment by duganchen** [comment]
The image is huge because I took it on an HTPC. So: large font size.

Just go to the Settings tab first. There will be buttons to add the source port and the IWAD. They'll show up in the Main tab after they're added there.
