### ISSUE TITLE
Store the configuration inside the ZDL Launcher folder

### ISSUE THREAD

**Issue by d0k3** [qbasicer/qzdl#59]
Right now, the configuration file is stored here:
``[USER_FOLDER]/AppData/Roaming/Vectec Software/qzdl.ini``

For this reason, ZDL Launcher is not truly portable. Can you change this so that the configuration file is stored inside the application folder? You could make this an alternative, for example, if ``qzdl.ini`` is found inside the application folder use it, otherwise keep the current handling.

I believe the necessary change is made here:
https://github.com/qbasicer/qzdl/blob/master/qzdl.cpp#L65
(if it is already changed there, I'm just waiting for a new release, I guess)

Sidenotes: What about a new release? This is more active than that other ZDL (which is actually a fork of yours), and the updater in the last release has long stopped working. If you decide to release, maybe also tell us what sets this apart from the other fork.

**Comment by duganchen** [comment]
It was looking for a file with the wrong name, zdl.ini and not qZDL.ini, but apart from that it was working as expected.

The pull request fixes that.

As for the other ZDL forks: I'm actually aware of two:

Talon1024's
https://forum.zdoom.org/viewtopic.php?f=44&t=32596&start=150#p965627

lcferrum's:
https://forum.zdoom.org/viewtopic.php?f=44&t=32596&start=165#p1090566

But the short answer is that this is not a fork; it's the main branch.

**Comment by d0k3** [comment]
Great, thanks!

Now, can I download nightlies somewhere? Or, will there be a release soon?
