### ISSUE TITLE
I can|t host a Server

### ISSUE THREAD

**Issue by Toadfield** [qbasicer/qzdl#68]
When I try to host a Server and launch it,then a friend tries to join,then it just doesn't work.
Here are my settings:
https://i.imgur.com/0clfuxt.png
https://i.imgur.com/6hrAZAm.png
Do I do something wrong?

**Comment by duganchen** [comment]
This is something I've never tested, so I have a big question.

Do you have this issue in both the master branch and in the last binary release (3.2.2.3)?

**Comment by Toadfield** [comment]
I only tested the two versions that are available in the AUR (qzdl 3.3.0.0-1 and qzdl-git 491.68668f1-1).
They both don't work,is version 3.2.2.3 available for Arch based Distros?
btw I tested it with a windows user,so could that be the problem?

**Comment by qbasicer** [comment]
> is version 3.2.2.3 available for Arch based Distros

We do not maintain nor have any affiliation with the AUR release at https://aur.archlinux.org/packages/qzdl/

Closing this issue as it's now stale.

**Comment by duganchen** [comment]
I wonder if this is fixed now?

https://github.com/qbasicer/qzdl/pull/73
