### ISSUE TITLE
ZDL wont forget original file location

### ISSUE THREAD

**Issue by MO3BIUM** [qbasicer/qzdl#72]
Hi, I have been using ZDL with Gzdoom VR for a couple of years. I have a particular issue and have not found any resolve.  I usually have D:\ as my gaming drive. For my last re-install several months ago finishing off my new tower build I left my DVD drive as default D:  

So I finally decided to rearrange my drive letters the way I want them. This caused the issue that I am now having.  Even after I delete every bit of GZDoom and ZDL off of my machine it automatically picks E: (the location of the original install) and selects non-existing files, even if I change the location ZDL says "failed to launch the process" . So is this some bug or are there cached files hiding somewhere that need to be deleted?   

gzdoom VR  itself still works just fine, ZDL makes it all superior. so I would love to hear an answer?

**Comment by qbasicer** [comment]
@MO3BIUM: How are you launching ZDL?  By default, ZDL looks for `qZDL.ini` within the application directory (https://github.com/qbasicer/qzdl/blob/master/qzdl.cpp#L65).  The other location it may be is in `C:/Users/USERNAME/AppData/Roaming/Vectec Software/qZDL/` (although I cannot confirm the exact path, perhaps @duganchen can).  Check either of these paths, and you should be safe to just remove them if you want to start fresh.

**Comment by duganchen** [comment]
There's an "About ZDL" dialog box that shows where the settings are kept.

Close ZDL and delete it.

**Comment by qbasicer** [comment]
@MO3BIUM please re-open this issue if @duganchen's instructions do not solve your problem

**Comment by MO3BIUM** [comment]
Yup! that did it. may thanks. I was getting pretty annoyed. I was looking through the Docus/mty games & appdata% and didnt see anything recognizable and figured it would be best to ask the devs. - Cheers mate.
