### ISSUE TITLE
qt6 support

### ISSUE THREAD

**Issue by wantija** [qbasicer/qzdl#91]
in the future, is a qt6 port planned? qt5 is end-of-life now.

**Comment by duganchen** [comment]
I'm for it. My only reservation is that @Talon1024 did work to support earlier versions of Qt (https://github.com/qbasicer/qzdl/pull/80), and a reasonable implementation of Qt 6 support (https://doc.qt.io/qt-6/cmake-qt5-and-qt6-compatibility.html) would drop support for those legacy Qt versions. Basically, we'd support Qt 6, and the very latest version of Qt 5 only.

**Comment by wantija** [comment]
Would making a seperate qt5 branch be a thing to do and a release for kde5/win 7 users. Then focus on qt6 after the confirmation?

Mar 23, 2024, 17:53 by ***@***.***:

**Comment by duganchen** [comment]
Yeah, I deleted that after thinking about it a a bit. The PR I entered works with everything.
